mithorium-common: sepolicy: Label qcom extcon sysfs
Log:
W/ExtconUEventObserver Unable to read /sys/devices/platform/soc/200f000.qcom,spmi/spmi-0/spmi0-02/200f000.qcom,spmi:qcom,pmi8950@2:qcom,qpnp-smbcharger/extcon/extcon1/cable.0/name. This probably means the selinux policies need to be changed.
java.io.FileNotFoundException: /sys/class/extcon/extcon1/cable.0/name: open failed: EACCES (Permission denied)

W/ExtconUEventObserver Unable to read /sys/devices/platform/soc/soc:qcom,mdss_wb_panel/extcon/extcon0/cable.0/name. This probably means the selinux policies need to be changed.
java.io.FileNotFoundException: /sys/class/extcon/extcon0/cable.0/name: open failed: EACCES (Permission denied)

[
android.ui: type=1400 audit(0.0:30): avc:  denied  { read } for  name="name" dev="sysfs" ino=31380 scontext=u:r:system_server:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
android.ui: type=1400 audit(0.0:31): avc:  denied  { read } for  name="name" dev="sysfs" ino=42933 scontext=u:r:system_server:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
android.ui: type=1400 audit(0.0:32): avc:  denied  { read } for  name="name" dev="sysfs" ino=42930 scontext=u:r:system_server:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
ExtconUEventObserver: Unable to read /sys/devices/platform/soc/soc:qcom,mdss_wb_panel/extcon/extcon0/cable.0/name. This probably means the selinux policies need to be changed.
ExtconUEventObserver: java.io.FileNotFoundException: /sys/class/extcon/extcon0/cable.0/name: open failed: EACCES (Permission denied)
ExtconUEventObserver: Unable to read /sys/devices/platform/soc/200f000.qcom,spmi/spmi-0/spmi0-02/200f000.qcom,spmi:qcom,pmi632@2:qcom,qpnp-smb5/extcon/extcon1/cable.1/name. This probably means the selinux policies need to be changed.
ExtconUEventObserver: java.io.FileNotFoundException: /sys/class/extcon/extcon1/cable.1/name: open failed: EACCES (Permission denied)
ExtconUEventObserver: Unable to read /sys/devices/platform/soc/200f000.qcom,spmi/spmi-0/spmi0-02/200f000.qcom,spmi:qcom,pmi632@2:qcom,qpnp-smb5/extcon/extcon1/cable.0/name. This probably means the selinux policies need to be changed.
ExtconUEventObserver: java.io.FileNotFoundException: /sys/class/extcon/extcon1/cable.0/name: open failed: EACCES (Permission denied)
ExtconUEventObserver: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
]

Change-Id: c5ae58b9a7f85772e0c21fb45c470ca2e226f409
Signed-off-by: TogoFire <italomellopereira@gmail.com>
Signed-off-by: tavukkdoner <166294260+tavukkdoner@users.noreply.github.com>